Repository codesquad-members-2023/gaemi-marble-team-04, pull requests merged in 2023-10, with the labels that each got.

#7 [FE] 프로젝트 초기 세팅
  fe/.eslintrc.cjs
  fe/.prettierrc.json
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Home.tsx
  fe/src/components/Login.tsx
  fe/src/main.tsx
  fe/src/router/router.tsx
  fe/src/styles/common.ts
  fe/src/styles/designSystem.ts
  fe/src/styles/style.d.ts
  fe/vite.config.ts
Labels: refactor, fe, chore

#8 [FE] 로그인/회원가입 페이지 UI 구현
  fe/.eslintrc.cjs
  fe/src/App.tsx
  fe/src/components/Login.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/router/router.tsx
  fe/src/styles/common.ts
  fe/src/styles/designSystem.ts
  fe/vite.config.ts
Labels: fe, UI

#10 [FE] 주요 패키지 설치 및 라우팅 설정 변경
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
  fe/src/api/index.ts
  fe/src/components/Layout.tsx
  fe/src/router/constants.ts
  fe/src/router/router.tsx
  fe/src/store/index.ts
Labels: fe, chore

#14 [BE] Request handling 구조 설계 구현
  be/build.gradle
  be/src/main/java/codesquad/gaemimarble/config/CorsConfig.java
  be/src/main/java/codesquad/gaemimarble/config/FilterConfig.java
  be/src/main/java/codesquad/gaemimarble/config/WebSocketConfig.java
  be/src/main/java/codesquad/gaemimarble/filter/AuthorizationFilter.java
  be/src/main/java/codesquad/gaemimarble/filter/WebSocketHandler.java
  be/src/main/java/codesquad/gaemimarble/game/GameMessage.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameReadyRequest.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameStockBuyRequest.java
  be/src/main/java/codesquad/gaemimarble/game/repository/GameRepository.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, be

#15 [FE] 로그인/회원가입/로그아웃 기능구현
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
  fe/src/api/index.ts
  fe/src/main.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/HomePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/router/ProtectedRoute.tsx
  fe/src/router/router.tsx
  fe/src/store/index.ts
  fe/src/styles/common.ts
Labels: feat, fe

#17 [FE] 홈 화면 작업
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/index.ts
  fe/src/assets/logout.svg
  fe/src/assets/plus.svg
  fe/src/assets/sample.svg
  fe/src/components/Header.tsx
  fe/src/components/Layout.tsx
  fe/src/components/Modal/EnterModal/EnterModal.tsx
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/icon/Icon.tsx
  fe/src/components/icon/icons.ts
  fe/src/hooks/useHover.ts
  fe/src/hooks/useOutsideClick.ts
  fe/src/main.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/router/ProtectedRoute.tsx
  fe/src/router/router.tsx
  fe/src/styles/common.ts
  fe/src/styles/designSystem.ts
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: fe, UI

#18 [FE] 홈 페이지 방 생성 및 이동 기능 구현
  fe/src/api/index.ts
  fe/src/components/Layout.tsx
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/hooks/useHover.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/GamePage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/router/constants.ts
  fe/src/router/router.tsx
  fe/src/styles/common.ts
Labels: feat, fe

#22 [FE] 게임 페이지 기능 및 UI 구현
  fe/src/api/ws.ts
  fe/src/assets/icon/antBasic.svg
  fe/src/assets/icon/antFire.svg
  fe/src/assets/icon/antHoney.svg
  fe/src/assets/icon/antWater.svg
  fe/src/assets/icon/exit.svg
  fe/src/assets/icon/plus.svg
  fe/src/assets/icon/sample.svg
  fe/src/assets/logo/google.png
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Modal/EnterModal/EnterModal.tsx
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/components/Player/PlayerTestModal.tsx
  fe/src/components/icon/icons.ts
  fe/src/hooks/useHover.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/GamePage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/constants.ts
  fe/src/store/constants.ts
  fe/src/store/index.ts
  fe/src/store/reducer/player/contants.ts
  fe/src/store/reducer/player/index.ts
  fe/src/store/reducer/player/type.ts
  fe/src/store/reducer/player/usePlayerReducer.ts
  fe/src/store/reducer/stock/index.ts
  fe/src/store/reducer/stock/type.ts
  fe/src/store/type.ts
  fe/src/styles/designSystem.ts
Labels: feat, fe

#24 [FE] 보드게임판 UI 구현
  fe/src/assets/images/apple.png
  fe/src/assets/images/codesquad.png
  fe/src/assets/images/gold-card.png
  fe/src/assets/images/google.png
  fe/src/assets/images/gs.png
  fe/src/assets/images/hanatour.png
  fe/src/assets/images/hanwha.png
  fe/src/assets/images/hermes.png
  fe/src/assets/images/hyundai.png
  fe/src/assets/images/index.ts
  fe/src/assets/images/jail.png
  fe/src/assets/images/koreanAir.png
  fe/src/assets/images/mcdonalds.png
  fe/src/assets/images/musinsa.png
  fe/src/assets/images/nongshim.png
  fe/src/assets/images/pfizer.png
  fe/src/assets/images/rocket.png
  fe/src/assets/images/samsungBio.png
  fe/src/assets/images/starkIndustry.png
  fe/src/assets/images/start-arrow.png
  fe/src/assets/images/stock-up.png
  fe/src/assets/images/tax.png
  fe/src/assets/images/tesla.png
  fe/src/assets/images/twitter.png
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/pages/GamePage.tsx
Labels: fe, UI

#27 [FE] 플레이어 토큰 이동기능 구현
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/PlayerToken.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/store/playerToken/index.ts
  fe/src/styles/designSystem.ts
  fe/src/utils/index.ts
  fe/tsconfig.json
Labels: feat

#29 [FE] 게임 상태 관리
  fe/package-lock.json
  fe/package.json
  fe/src/assets/logo/google.png
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Player/LeftPlayers.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/components/Player/PlayerTestModal.tsx
  fe/src/components/Player/RightPlayers.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/GamePage.tsx
  fe/src/store/constants.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/player/contants.ts
  fe/src/store/reducer/player/index.ts
  fe/src/store/reducer/player/type.ts
  fe/src/store/reducer/player/usePlayerReducer.ts
  fe/src/store/reducer/stock/index.ts
  fe/src/store/reducer/stock/type.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
  fe/src/store/type.ts
Labels: feat, fe

#35 [BE] feat: be cicd workflow
  .github/workflows/main.yml
  be/Dockerfile
  docker-compose.yml
  nginx/nginx.conf
Labels: feat, be

#33 [FE] 전체 주식 현황판
  fe/src/assets/icon/statusBoard.svg
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/PlayerTestModal.tsx
  fe/src/components/Modal/StatusBoardModal/StatusBoardModal.tsx
  fe/src/components/Modal/StatusBoardModal/StatusBoardModalContent.tsx
  fe/src/components/icon/icons.ts
  fe/src/pages/GamePage.tsx
  fe/src/styles/GlobalStyle.ts
Labels: fe, UI

#38 [FE] 프론트엔드 자동배포 테스트
  .github/workflows/deploy.yml
Labels: fe, chore

#41 [BE] 기능 구현, 배포 완료
  be/src/main/java/codesquad/gaemimarble/config/CorsConfig.java
  be/src/main/java/codesquad/gaemimarble/filter/WebSocketHandler.java
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/dto/GameMapper.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameMessage.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameCellResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameEndTurnResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameEventResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/generalStatusBoard/GameStatusBoardResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/generalStatusBoard/GameStockStatusResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/userStatusBoard/GameUserBoardResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/userStatusBoard/GameUserStatusBoardResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/userStatusBoard/StockNameResponse.java
  be/src/main/java/codesquad/gaemimarble/game/entity/CurrentPlayerInfo.java
  be/src/main/java/codesquad/gaemimarble/game/entity/GameStatus.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Player.java
  be/src/main/java/codesquad/gaemimarble/game/entity/TypeConstants.java
  be/src/main/java/codesquad/gaemimarble/game/repository/GameRepository.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
  be/src/main/resources/application.yml
  be/src/test/java/codesquad/gaemimarble/Test1.java
Labels: feat, fix, be

#40 [FE] 게임페이지 리팩토링
  .github/workflows/deploy.yml
  fe/src/assets/icon/antBasic.svg
  fe/src/assets/icon/antFire.svg
  fe/src/assets/icon/antHoney.svg
  fe/src/assets/icon/antWater.svg
  fe/src/assets/icon/arrowLeft.svg
  fe/src/assets/icon/arrowRight.svg
  fe/src/components/Modal/InviteModal/InviteModal.tsx
  fe/src/components/Modal/InviteModal/InviteModalContent.tsx
  fe/src/components/Player/EmptyCard.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/components/Player/PlayerStockTooltip.tsx
  fe/src/components/Player/constants.ts
  fe/src/components/icon/icons.ts
  fe/src/hooks/useClickScrollButton.ts
  fe/src/hooks/useTooltipPosition.ts
  fe/src/mocks/handlers.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/useGameReducer.ts
Labels: refactor, fe

#45 [BE] 요구사항 반영 (이벤트결정, 전체현황판, 개인현황판, 게임입장, 로그아웃)
  .gitignore
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/dto/GameMapper.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameEventResultRequest.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameEnterResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameEventNameResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/userStatusBoard/GameUserStatusBoardResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/userStatusBoard/StockResponse.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Player.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
  be/src/main/java/codesquad/gaemimarble/user/controller/UserController.java
Labels: feat, fix, be, chore

#52 [BE] 감옥, 세금 구현 및 오류 수정, 추가 요청 처리 등
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/controller/SocketDataSender.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameBailRequest.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GamePrisonDiceRequest.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameExpenseResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GamePrisonDiceResponse.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Events.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Player.java
  be/src/main/java/codesquad/gaemimarble/game/entity/TypeConstants.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, fix, be

#55 [BE] 순간이동, 기업칸, 호재칸 도착 기능 구현
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameTeleportRequest.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Board.java
  be/src/main/java/codesquad/gaemimarble/game/entity/TypeConstants.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/Cell.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/Company.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/GoldCard.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/GoodNews.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/Prison.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/Start.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/Tax.java
  be/src/main/java/codesquad/gaemimarble/game/entity/ground/Teleport.java
  be/src/main/java/codesquad/gaemimarble/game/repository/GameRepository.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, be

#53 [FE] 게임 준비 기능과 이벤트 룰렛 구현
  fe/package-lock.json
  fe/package.json
  fe/src/api/fetcher.ts
  fe/src/assets/images/index.ts
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/Player/EmptyCard.tsx
  fe/src/components/Player/LeftPlayers.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/RightPlayers.tsx
  fe/src/hooks/useGetSocketUrl.ts
  fe/src/main.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/GamePage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/store/index.ts
  fe/src/store/playerToken/index.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
  fe/src/styles/designSystem.ts
  server/app.js
Labels: feat, fe

#56 [FE] 주식 매수 기능 구현
  fe/src/assets/icon/arrowDown.svg
  fe/src/assets/icon/arrowUp.svg
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Modal/EnterModal/EnterModalContent.tsx
  fe/src/components/Modal/PlayerTestModal.tsx
  fe/src/components/Modal/StatusBoardModal/StatusBoardModalContent.tsx
  fe/src/components/Modal/StockModal/StockBuyModal.tsx
  fe/src/components/Modal/StockModal/StockBuyModalContent.tsx
  fe/src/components/Player/LeftPlayers.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/RightPlayers.tsx
  fe/src/components/icon/icons.ts
  fe/src/pages/HomePage.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/utils/index.ts
Labels: feat, fe

#59 [BE] 게임 시작 시 개인 현황판 추가 응답
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, be
