Repository codesquad-members-2023/gaemi-marble-team-04, pull requests merged in 2023-11, with the labels that each got.

#60 [FE] 주식 매도 기능 구현
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Header/HomeHeader.tsx
  fe/src/components/Modal/StatusBoardModal/StatusBoardModalContent.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModal.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModalContent.tsx
  fe/src/components/Modal/StockSellModal/StockSellModal.tsx
  fe/src/components/Modal/StockSellModal/StockSellModalContent.tsx
  fe/src/components/Modal/StockSellModal/StockSellTableData.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/PlayerStock.tsx
  fe/src/components/Player/PlayerStockTooltip.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
Labels: feat, fe

#62 [FE] 토큰 이동 버그 수정 및 감옥칸 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/PlayerToken.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Modal/EventModal/EventModal.tsx
  fe/src/components/Modal/EventModal/EventModalContent.tsx
  fe/src/pages/HomePage.tsx
  fe/src/store/playerToken/index.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
Labels: feat, fix, fe

#67 [BE] 강탈 기능, 개인 현황판 수정
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/dto/request/GameRobRequest.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Events.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Player.java
  be/src/main/java/codesquad/gaemimarble/game/entity/Stock.java
  be/src/main/java/codesquad/gaemimarble/game/entity/TypeConstants.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, be

#68 [BE] 칸도착-황금카드, 소켓 에러처리, 오타 수정
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/controller/SocketDataSender.java
  be/src/main/java/codesquad/gaemimarble/game/dto/SocketErrorResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/GameGoldCardResponse.java
  be/src/main/java/codesquad/gaemimarble/game/entity/GoldCard.java
  be/src/main/java/codesquad/gaemimarble/game/entity/TypeConstants.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, fix, be

#71 [FE] 순간이동 기능 구현 및 기존 버그들 수정
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/hooks/useMoveToken.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
Labels: feat, fix

#74 [FE] 최종발표전 버그 수정 및 룰렛 타이머 구현
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Layout.tsx
  fe/src/components/Modal/StockSellModal/StockSellModalContent.tsx
  fe/src/components/Player/LeftPlayers.tsx
  fe/src/components/Player/PlayerCard.tsx
  fe/src/components/Player/RightPlayers.tsx
  fe/src/pages/GamePage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
Labels: feat, fix, fe

#73 [FE] 황금 카드 기능
  fe/src/components/GameBoard/CenterArea.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/Modal/GoldCardModal/GoldCardModal.tsx
  fe/src/components/Modal/GoldCardModal/GoldCardModalContent.tsx
  fe/src/pages/GamePage.tsx
  fe/src/pages/constants.ts
  fe/src/store/reducer/constants.ts
  fe/src/store/reducer/index.ts
  fe/src/store/reducer/type.ts
  fe/src/store/reducer/useGameReducer.ts
  fe/src/styles/designSystem.ts
Labels: feat, fe

#76 [FE] 코드 리팩토링, ui 작업 및 사운드 효과 추가
  fe/public/sound/roulette.mp3
  fe/src/assets/images/gs.png
  fe/src/assets/images/hermes.png
  fe/src/assets/images/nongshim.png
  fe/src/assets/images/starkindustry.png
  fe/src/components/GameBoard/Cell.tsx
  fe/src/components/GameBoard/Dice.tsx
  fe/src/components/GameBoard/GameBoard.tsx
  fe/src/components/GameBoard/PlayerToken.tsx
  fe/src/components/GameBoard/Roulette.tsx
  fe/src/components/GameBoard/constants.ts
  fe/src/components/Header/GameHeader.tsx
  fe/src/components/Modal/StatusBoardModal/StatusBoardModalContent.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModal.tsx
  fe/src/components/Modal/StockBuyModal/StockBuyModalContent.tsx
  fe/src/components/Player/LeftPlayers.tsx
  fe/src/components/Player/PlayerInfo.tsx
  fe/src/components/Player/RightPlayers.tsx
  fe/src/components/icon/Icon.tsx
  fe/src/hooks/useSound.tsx
  fe/src/pages/GamePage.tsx
  fe/src/pages/constants.ts
Labels: refactor, fe, UI

#79 [BE] 게임 종료, 예외처리 구현
  be/src/main/java/codesquad/gaemimarble/exception/CustomException.java
  be/src/main/java/codesquad/gaemimarble/filter/WebSocketHandler.java
  be/src/main/java/codesquad/gaemimarble/game/controller/GameController.java
  be/src/main/java/codesquad/gaemimarble/game/controller/SocketDataSender.java
  be/src/main/java/codesquad/gaemimarble/game/dto/SocketErrorResponse.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/PlayerAsset.java
  be/src/main/java/codesquad/gaemimarble/game/dto/response/UserRankingResponse.java
  be/src/main/java/codesquad/gaemimarble/game/entity/GameStatus.java
  be/src/main/java/codesquad/gaemimarble/game/entity/TypeConstants.java
  be/src/main/java/codesquad/gaemimarble/game/service/GameService.java
Labels: feat, be
